CREATE TABLE type_list 
(
    type_code,
    type_name,
    type
);

INSERT INTO type_list (type_code, type_name, type) VALUES
	('ka-dia-yo', 'Digraf dengan diakritik (yōon dengan (han)dakuten)', 'katakana'),
	('ka-dia-go', 'Monograf dengan diakritik: gojūon dengan (han)dakuten', 'katakana'),
	('ka-di-yo', 'Digraf (yōon)', 'katakana'),
	('ka-mono-go', 'Monograf (gojūon)', 'katakana'),
	('hi-dia-yo', 'Digraf dengan diakritik (yōon dengan (han)dakuten)', 'hiragana'),
	('hi-dia-go', 'Monograf dengan diakritik: gojūon dengan (han)dakuten', 'hiragana'),
	('hi-di-yo', 'Digraf (yōon)', 'hiragana'),
	('hi-mono-go', 'Monograf (gojūon)', 'hiragana'),
	('kan', 'Kanji', 'kanji'),
	('adj-ku', 'kata sifat ku (kuno)', 'kata sifat'),
	('adj-shiku', 'Kata sifat shiku (kuno)', 'kata sifat'),
	('adj-t', 'kata sifat taru', 'kata sifat'),
	('adj-na', 'Kata sifat kata benda atau kata sifat semu (keiyodoshi)', 'kata sifat'),
	('adj-i', 'Kata sifat (keiyoushi)', 'kata sifat'),
	('adj-ix', 'Kata sifat (keiyoushi) - kelas yoi/ii', 'kata sifat'),
	('adv', 'Kata keterangan (fukushi)', 'kata keterangan'),
	('adv-to', 'Kata keterangan yang menggunakan partikel ke', 'kata keterangan'),
	('adj-nari', 'Bentuk arkaik/formal dari na-adjektiva', 'kata sifat'),
	('aux', 'Kata bantu', 'kata bantu'),
	('aux-adj', 'Kata sifat bantu', 'kata bantu'),
	('aux-v', 'Kata kerja bantu', 'kata bantu'),
	('conj', 'Konjungsi', 'konjungsi'),
	('cop', 'Kopula', 'kopula'),
	('ctr', 'Penghitung', 'perhitungan'),
	('exp', 'Ekspresi (frasa, klausa, dll.)', 'ekspresi'),
	('v5aru', 'Kata kerja Godan - -aru kelas khusus', 'kata kerja'),
	('v5k-s', 'Kata kerja Godan - kelas khusus Iku/Yuku', 'kata kerja'),
	('v5b', 'Kata kerja Godan dengan akhiran bu', 'kata kerja'),
	('v5g', 'Kata kerja Godan dengan akhiran gu', 'kata kerja'),
	('v5k', 'Kata kerja Godan dengan akhiran ku', 'kata kerja'),
	('v5m', 'Kata kerja Godan dengan akhiran mu', 'kata kerja'),
	('v5n', 'Kata kerja Godan dengan akhiran nu', 'kata kerja'),
	('v5r', 'Kata kerja bahasa Godan dengan akhiran ru', 'kata kerja'),
	('v5r-i', 'Kata kerja bahasa Godan dengan akhiran ru (kata kerja tidak beraturan)', 'kata kerja'),
	('v5s', 'Kata kerja bahasa Godan dengan akhiran su', 'kata kerja'),
	('v5t', 'Kata kerja bahasa Godan dengan akhiran tsu', 'kata kerja'),
	('v5u', 'Kata kerja Godan dengan akhiran u', 'kata kerja'),
	('v5u-s', 'Kata kerja Godan dengan akhiran u (kelas khusus)', 'kata kerja'),
	('v1', 'Kata kerja Ichidan', 'kata kerja'),
	('v1-s', 'Kata kerja Ichidan - kelas khusus kureru', 'kata kerja'),
	('vz', 'Kata kerja Ichidan - kata kerja zuru (bentuk alternatif dari kata kerja -jiru)', 'kata kerja'),
	('int', 'Kata seru (kandoushi)', 'kata seru'),
	('vi', 'Kata kerja intransitif', 'kata kerja'),
	('vn', 'Kata kerja nu tidak beraturan', 'kata kerja'),
	('vr', 'Kata kerja ru tidak beraturan, bentuk biasa diakhiri dengan -ri', 'kata kerja'),
	('vk', 'Kata kerja kuru - kelas khusus', 'kata kerja'),
	('v2d-s', 'Kata kerja Nidan (kelas rendah) dengan akhiran dzu (arkhais)', 'kata kerja'),
	('v2g-s', 'Kata kerja Nidan (kelas rendah) dengan akhiran gu (kuno)', 'kata kerja'),
	('v2h-s', 'Kata kerja Nidan (kelas rendah) dengan akhiran hu/fu (kuno)', 'kata kerja'),
	('v2k-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran ku (arkhais)', 'kata kerja'),
	('v2m-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran mu (arkhais)', 'kata kerja'),
	('v2n-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran nu (arkhais)', 'kata kerja'),
	('v2r-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran ru (arkhais)', 'kata kerja'),
	('v2s-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran su (arkhais)', 'kata kerja'),
	('v2t-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran tsu (arkhais)', 'kata kerja'),
	('v2w-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran u dan konjugasi we (arkhais)', 'kata kerja'),
	('v2y-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran yu (kuno)', 'kata kerja'),
	('v2z-s', 'Kata kerja Nidan (kelas bawah) dengan akhiran zu (kuno)', 'kata kerja'),
	('v2b-s', 'Kata kerja Nidan (kelas atas) dengan akhiran bu (arkhais)', 'kata kerja'),
	('v2g-s', 'Kata kerja Nidan (kelas atas) dengan akhiran gu (arkhais)', 'kata kerja'),
	('v2h-s', 'Kata kerja Nidan (kelas atas) dengan akhiran hu/fu (arkhais)', 'kata kerja'),
	('v2k-s', 'Kata kerja Nidan (kelas atas) dengan akhiran ku (arkhais)', 'kata kerja'),
	('v2r-s', 'Kata kerja Nidan (kelas atas) dengan akhiran ru (arkhais)', 'kata kerja'),
	('v2t-s', 'Kata kerja Nidan (kelas atas) dengan akhiran tsu (arkhais)', 'kata kerja'),
	('v2y-s', 'Kata kerja Nidan (kelas atas) dengan akhiran yu (arkhais)', 'kata kerja'),
	('v2a-s', 'Kata kerja Nidan (kelas atas) dengan akhiran u (arkhais)', 'kata kerja'),
	('n', 'Kata benda (umum) (futsuumeishi)', 'kata benda'),
	('vs', 'Kata benda atau partisip yang mengambil aux. kata kerja suru', 'kata benda'),
	('adj-f', 'Kata benda atau kata kerja yang bertindak secara prenominal', 'kata benda'),
	('n-pref', 'Kata benda, digunakan sebagai awalan', 'kata benda'),
	('n-suf', 'Kata benda, digunakan sebagai akhiran', 'kata benda'),
	('adj-no', 'Kata benda yang dapat menggunakan partikel kasus genitif tidak', 'kata benda'),
	('num', 'Angka', 'angka'),
	('prt', 'Partikel', 'partikel'),
	('adj-pn', 'Kata sifat pra-kata benda (rentaishi)', 'kata sifat'),
	('pref', 'Awalan', 'awalan akhiran'),
	('pn', 'Kata ganti', 'kata ganti'),
	('vs-c', 'Su kata kerja - pendahulu suru modern', 'kata kerja'),
	('suf', 'Akhiran', 'awalan akhiran'),
	('vs-i', 'Kata kerja suru - termasuk', 'kata kerja'),
	('vs-s', 'Kata kerja suru - kelas khusus', 'kata kerja'),
	('vt', 'Kata kerja transitif', 'kata kerja'),
	('unc', 'Tidak diklasifikasikan', 'kata benda'),
	('v-unspec', 'Kata kerja tidak ditentukan', 'kata kerja'),
	('v4b', 'Kata kerja Yodan dengan akhiran bu (kuno)', 'kata kerja'),
	('v4g', 'Kata kerja Yodan dengan akhiran gu (kuno)', 'kata kerja'),
	('v4h', 'Kata kerja Yodan dengan akhiran hu/fu (kuno)', 'kata kerja'),
	('v4k', 'Kata kerja Yodan dengan akhiran ku (kuno)', 'kata kerja'),
	('v4m', 'Kata kerja Yodan dengan akhiran mu (kuno)', 'kata kerja'),
	('v4n', 'Kata kerja Yodan dengan akhiran ru (kuno)', 'kata kerja'),
	('v4s', 'Kata kerja Yodan dengan akhiran su (kuno)', 'kata kerja'),
	('v4t', 'Kata kerja Yodan dengan akhiran tsu (arkhais)', 'kata kerja');